### ISSUE TITLE
Why does Font-Awesome depend on Bootstrap 2.3.2?

### ISSUE THREAD

**Issue by gitblit** [webjars/font-awesome#12]
https://github.com/webjars/font-awesome/blob/master/pom.xml#L55

**Comment by jamesward** [comment]
I dunno.  It seems like at some point the upstream project depended on Bootstrap.  Maybe that is no longer or never true.  Can you confirm?  If so we will remove the transitive dependency.

**Comment by gitblit** [comment]
I downloaded the 4.3 zip and Bootstrap is not bundled. It's also not listed as a requirement here: https://fortawesome.github.io/Font-Awesome/get-started

I think it's safe to remove it.
