### ISSUE TITLE
Glitch with version paths inside jar relative to the artifact version

### ISSUE THREAD

**Issue by gitblit** [webjars/font-awesome#14]
For most of the rebuilds of Webjars the `-n` artifact version suffix matches the version path within the jar file.  This allows me to harvest the Maven version from `pom.properties` and know the appropriate base path for this webjar's resources.

In the 4.3.0-1 and 4.3.0-2 rebuilds this is not the case.  Those rebuilds preserve the "4.3.0" version path.  This seems inconsistent with most other rebuilt Webjars I have surveyed.

**Comment by jamesward** [comment]
It should match so this is a bug.  Fixing it now and releasing `4.3.0-3`.

**Comment by gitblit** [comment]
Bueno.  Thanks @jamesward .
