### ISSUE TITLE
Missing webfonts ?

### ISSUE THREAD

**Issue by PlassJ** [webjars/font-awesome#29]
After #28 is fixed i am try again to make it work.
I try to make this webjar work with Primefaces 6.2.x and disabled fontawsome support, so there should be no interferences.
But the only thing i can get display at ui is a [] icon.

Version 4.x working:
pom.xml
`<dependency>`
`     <groupId>org.webjars</groupId>`
`     <artifactId>font-awesome</artifactId>`
`     <version>4.7.0</version>`
`</dependency>`

*.xhtml
`<h:outputStylesheet library="webjars" name="font-awesome/4.7.0/css/font-awesome-jsf.css" />`

Version 5.0.10 not working:
pom.xml
`<dependency>`
`	<groupId>org.webjars</groupId>`
`	<artifactId>font-awesome</artifactId>`
`	<version>5.0.10</version>`
`</dependency>`

*.xhtml
`<h:outputStylesheet library="webjars" name="font-awesome/5.0.10/web-fonts-with-css/css/fontawesome-jsf.css" />`

So the path to the fontawesome-jsf.css has changed.
Could it be that location of the webfont also changed ? 

After using the fontawesome-all-jsf.css file i could see error messages about missing fonts in the browser console:
`GET http://localhost/foobar/javax.faces.resource/font-awesome/5.0.10/web-fonts-with-css/webfonts/fa-solid-900.woff2 404 (Not Found)`

Any suggestions how to solve this ?

Or is this a font-awesome Problem ? 

Thank you in advance

**Comment by Lynx12** [comment]
Yes, the folder structure has changed with Font Awesome 5 but the regex pattern in the pom.xml wan't modified. That should be fixed, because the released version 5.0.13 is not working.

**Comment by jamesward** [comment]
Can someone send a PR?  Thanks!

**Comment by melloware** [comment]
@PlassJ I think you can close this ticket.  To make it work with PF 6.2.12 or higher do this...

**web.xml**
```xml
<context-param>
     <param-name>primefaces.FONT_AWESOME</param-name>
     <param-value>false</param-value>         
</context-param>
```

**pom.xml** (add the webjar)
```xml
<dependency>
     <groupId>org.webjars</groupId>
     <artifactId>font-awesome</artifactId>
     <version>5.8.1</version>
</dependency>
```

Declare these two files in my layout XHTML.

```xml
<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/all-jsf.css" />
<h:outputStylesheet library="webjars" name="font-awesome/5.8.1/css/v4-shims.min-jsf.css" />
```

**Comment by PlassJ** [comment]
@melloware I did not work with PF and webjars for a while. But if you can confirm this works i will close this issue.
Btw i am back to PF now =)

**Comment by melloware** [comment]
@PlassJ welcome back!  and yes I am using my setup in PF 6.2.20 with absolutely no issues.
