### ISSUE TITLE
Please review 5.0.13-1

### ISSUE THREAD

**Issue by mixcloud-downloader** [webjars/font-awesome#32]
The upgrade from 5.0.13 to 5.0.13-1 has a completely different folder structure and it seems content is missing, namely things like font-awesome/svg-with-js/js/fontawesome-all.min.js. Is this on purpose?

![5 0 13](https://user-images.githubusercontent.com/24543284/41710839-f3a006e2-7546-11e8-8506-deb0a9f7c0ea.png)

![5 0 13-1](https://user-images.githubusercontent.com/24543284/41710856-fda3093c-7546-11e8-8ff2-2262dcc372ae.png)

**Comment by ceoche** [comment]
Moreover, version number in resources path has changed for 5.0.13-1, but in css files, font-family are still referring to 5.0.13 : 
`src: url("#{resource['webjars:font-awesome/5.0.13/webfonts/fa-brands-400.eot']}&#");`

How is it suppose to work ?

**Comment by mixcloud-downloader** [comment]
I'm missing the folder svg-with-js/ for "SVG with JavaScript". From what I can tell the folders in 5.0.13-1 are not consistent with the font-awesome documentation. 5.0.13 however is. The folders less and scss suggest that this is the unprocessed font awesome package which is not suitable for direct use as 5.0.13 was.

**Comment by jamesward** [comment]
@DennisRippinger can you look into this?

For reference: #31 is what changed this.

**Comment by mixcloud-downloader** [comment]
Oh, I see. #31 removed svg-with-js. Please add it back. Font-awesome promotes "SVG & JS" as our new and advanced SVG & JS framework. The additional weight doesn't really hurt a web application, but if you want to reduce the weight then it would make more sense to split this package into each flavour.

**Comment by jamesward** [comment]
In the meantime... `5.0.13` should work just fine for you.

**Comment by DennisRippinger** [comment]
Sorry for the inconvenience of stripping the entire distribution, with #33 it should be back. 

My point is that the distribution is now **much** larger than my actual application, when only a tiny fraction is needed. I think for the future I will put something together with the [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/examples/unpacking-artifacts.html) to just extract what is needed for my cases.

**Comment by jamesward** [comment]
This is being released as `5.0.13-2`.
