### ISSUE TITLE
5.8.2 showing square box instead of image

### ISSUE THREAD

**Issue by nghianja** [webjars/font-awesome#49]
Hi,

I integrated version 5.8.2 via Gradle ` implementation("org.webjars:font-awesome:5.8.2")` and included the stylesheet and script as follow:
`<link rel="stylesheet" href="webjars/font-awesome/5.8.2/css/fontawesome.min.css">`
`<script src="webjars/font-awesome/5.8.2/js/fontawesome.min.js"></script>`

When I wanted to use the icon 'language' as in `<i class="fas fa-language"></i>`, only a square box is displayed.

May I know is there any resolution or workaround to this?

Thank you very much.

**Comment by jamesward** [comment]
Are there are any errors in your browser console?

**Comment by nghianja** [comment]
Nope. There is no error in the console.
By the way, I am using Chrome and I have yet to test on other browsers.

**Comment by jamesward** [comment]
Can you validate the css was loaded correctly and that the `fas fa-language` `class` are correct for that version?

**Comment by nghianja** [comment]
Hi, I have attached 2 screenshots. The first is the one using the webjar with the css loaded and you can see the square box that is supposed to be the icon. The second is the one using the fontawesome kit script of the same version to load the icon and it is shown.

<img width="328" alt="Screenshot 2019-06-09 at 1 02 46 PM" src="https://user-images.githubusercontent.com/1296470/59155267-07252080-8ab8-11e9-8af5-61e34e83bd81.png">
<img width="326" alt="Screenshot 2019-06-09 at 1 07 41 PM" src="https://user-images.githubusercontent.com/1296470/59155268-0e4c2e80-8ab8-11e9-85c8-435fd0c62860.png">

**Comment by jamesward** [comment]
In the second one you are using `5.9.0` - perhaps that is making a difference?

**Comment by nghianja** [comment]
I have changed the fontawesome kit to 5.8.2 and it still works. So it seems the problem is not with the version.

<img width="321" alt="Screenshot 2019-06-10 at 1 11 29 AM" src="https://user-images.githubusercontent.com/1296470/59162071-6ec18700-8b1d-11e9-9085-2df7e7a4e6db.png">

**Comment by jamesward** [comment]
Thanks for testing that.  It appears that the `fontawesome.min.css` may not load the fonts.  I wonder if you have to load them manually or use a different css file.  Not totally sure since I haven't used fontawesome in a while.

**Comment by jamesward** [comment]
It looks like you might also need to add:
```
<link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet">
```
Or possibly just the `all.css` file.

**Comment by nghianja** [comment]
I changed the links to 

`<link rel="stylesheet" th:href="@{/webjars/font-awesome/5.8.2/css/all.css}">` 

and 

`<script th:src="@{/webjars/font-awesome/5.8.2/js/all.js}"></script>` 

and it works.

Thank you very much for your help.

**Comment by jamesward** [comment]
Great!
