### ISSUE TITLE
Font Awesome not showing on jsp and Spring boot 

### ISSUE THREAD

**Issue by alewiwi** [webjars/font-awesome#59]
I am having a problem on showing FA icons on my web application. My Application is built using spring boot
I have the following configurations:

pom.xml
`
<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>font-awesome</artifactId>
			<version>5.13.1</version>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>webjars-locator</artifactId>
			<version>0.40</version>
		</dependency>
` 

application.properties
`
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.resources.static-locations="/webjars/**"
`

jsp file:
`<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Insert title here</title>
<link rel='stylesheet'
	href='/webjars/bootstrap/css/bootstrap.min.css'>
<link rel='stylesheet' href='/webjars/font-awesome/css/fontawesome.min.css'></link>
...
...
<c:forEach items="${todoList}" var="todo">
					<tr>
						<th scope="row">${todo.id}</th>
						<td>${todo.title}</td>
						<td>${todo.description}</td>
						<td>${ todo.user }</td>
						<td>${ todo.completed }</td>
						<td><span class="fa fa-trash"></span></td>
						<td><span class="fa fa-edit"></span></td>
					</tr>
				</c:forEach>
`

The problem is that i got a squares with byte code of the font icon on firefox. i'v tried t browse the page using Chrome, i got empty square.

The strange thing that the eclipse internal browser displays icons properly

**Comment by alewiwi** [comment]
i found the sol. in previous closed issue, instead of using:
`<link rel='stylesheet' href='/webjars/font-awesome/css/fontawesome.min.css'></link>`
i should use:
`<link rel='stylesheet' href='/webjars/font-awesome/css/all.min.css'></link> `

**Comment by jamesward** [comment]
Glad you figured it out!
