### ISSUE TITLE
Request for `org.webjars:font-awesome:6.6.0`

### ISSUE THREAD

**Issue by Ashish-CodeJourney** [webjars/font-awesome#81]
I would like to consume `org.webjars:font-awesome:6.6.0` from maven-central or https://webjars.com/. Currently the latest version available there is 6.5.2 only.

Please publish version 6.6.0 to maven-central. Or point me to where to file this request, if it belongs somewhere else. Thanks a lot :-)

**Comment by jamesward** [comment]
Most Classic WebJars are deployed when asked for. :) I've bumped this version and it will be available in the next few hours.

**Comment by Ashish-CodeJourney** [comment]
> Most Classic WebJars are deployed when asked for. :) I've bumped this version and it will be available in the next few hours.

Thank you 🙌
